services:
  sc2pulse-dev-proxy:
    image: ghcr.io/xjasonlyu/tun2socks:v2.7.0
    container_name: sc2pulse-dev-proxy
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun:/dev/net/tun"
    networks:
      - sc2pulse
    environment:
      - TUN_EXCLUDED_ROUTES=10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,127.0.0.0/8,169.254.0.0/16,100.64.0.0/10,224.0.0.0/4,255.255.255.255
    healthcheck:
      test: ["CMD-SHELL", "ip link show tun0"]
      interval: 15s
      timeout: 1s
      retries: 1
      start_period: 5s
      start_interval: 1s
